header:
  version: 23

machine: raspberrypi4-64
distro: poky

target:
  - core-image-minimal

repos:
  poky:
    url: https://git.yoctoproject.org/poky
    branch: scarthgap
    layers:
      meta:
      meta-poky:

  meta-raspberrypi:
    url: https://github.com/agherzan/meta-raspberrypi.git
    branch: scarthgap

  logistics-automation:
    layers:
      yocto/meta-logistics:

local_conf_header:
  logistics-base: |
    DL_DIR = "${TOPDIR}/../downloads"
    SSTATE_DIR = "${TOPDIR}/../sstate-cache"

    BB_NUMBER_THREADS = "4"
    PARALLEL_MAKE = "-j 4"

    INIT_MANAGER = "systemd"
    ENABLE_UART = "1"

    IMAGE_FSTYPES = "wic.bz2 wic.bmap"

    EXTRA_IMAGE_FEATURES += "debug-tweaks ssh-server-dropbear"

  licenses: |
    LICENSE_FLAGS_ACCEPTED += "synaptics-killswitch"
