#ifndef COMM_RX_CONFIG_H
#define COMM_RX_CONFIG_H

#include "app_timing.h"

#define COMM_RX_DMA_BUFFER_SIZE 256U
#define COMM_RX_DMA_RESTART_DELAY_MS 10U
#define COMM_RX_TASK_SERVICE_INTERVAL_MS 10U
#define COMM_RX_TASK_ALIVE_INTERVAL_MS APP_TIMING_HEALTH_PERIOD_MS
#define COMM_RX_LINK_TIMEOUT_MS APP_TIMING_UART_RX_TIMEOUT_MS

#define COMM_RX_HEALTH_DMA_START_FAILED 0x01000000UL
#define COMM_RX_HEALTH_DMA_OVERRUN 0x02000000UL
#define COMM_RX_HEALTH_UART_ERROR 0x03000000UL
#define COMM_RX_HEALTH_FLAG_WAIT_ERROR 0x04000000UL
#define COMM_RX_HEALTH_PARSER_ERROR 0x05000000UL
#define COMM_RX_HEALTH_CONTROL_QUEUE_FULL 0x06000000UL
#define COMM_RX_HEALTH_SAFETY_QUEUE_FULL 0x07000000UL
#define COMM_RX_HEALTH_TX_RESPONSE_QUEUE_FULL 0x08000000UL
#define COMM_RX_HEALTH_SAFETY_NOTIFY_FAILED 0x09000000UL

#if COMM_RX_DMA_BUFFER_SIZE == 0U
#error "CommRx DMA buffer size must be greater than zero"
#endif

#if COMM_RX_DMA_BUFFER_SIZE > 65535U
#error "CommRx DMA buffer must fit in the HAL UART uint16_t size"
#endif

#endif /* COMM_RX_CONFIG_H */
