#ifndef COMM_TX_CONFIG_H
#define COMM_TX_CONFIG_H

#include "app_timing.h"

#define COMM_TX_HEARTBEAT_INTERVAL_MS APP_TIMING_COMM_TX_HEARTBEAT_MS
#define COMM_TX_DMA_TIMEOUT_MS 50U
#define COMM_TX_ABORT_TIMEOUT_MS 20U
#define COMM_TX_RETRY_DELAY_MS 5U
#define COMM_TX_MAX_RETRIES 3U

#endif /* COMM_TX_CONFIG_H */
