#ifndef CONTROL_CONFIG_H
#define CONTROL_CONFIG_H

#include "app_timing.h"

#define CONTROL_TASK_MAX_COMMANDS_PER_CYCLE 4U
#define CONTROL_TASK_ALIVE_INTERVAL_MS APP_TIMING_HEALTH_PERIOD_MS
#define CONTROL_TASK_PENDING_RESPONSE_CAPACITY APP_TX_RESPONSE_QUEUE_DEPTH

#define CONTROL_HEALTH_MOTOR_INIT_FAILED 0x4D000001UL
#define CONTROL_HEALTH_MOTOR_OUTPUT_FAILED 0x4D000002UL
#define CONTROL_HEALTH_FLAG_WAIT_FAILED 0x4D000003UL
#define CONTROL_HEALTH_MOTOR_INHIBIT_RELEASE_FAILED 0x4D000004UL

#if CONTROL_TASK_MAX_COMMANDS_PER_CYCLE == 0U
#error "ControlTask must process at least one command per cycle"
#endif

#if CONTROL_TASK_PENDING_RESPONSE_CAPACITY == 0U
#error "ControlTask pending response capacity must be greater than zero"
#endif

#endif /* CONTROL_CONFIG_H */
