#ifndef CONTROL_CONFIG_H
#define CONTROL_CONFIG_H

#include "app_timing.h"

#define CONTROL_TASK_MAX_COMMANDS_PER_CYCLE 4U
#define CONTROL_TASK_ALIVE_INTERVAL_MS APP_TIMING_HEALTH_PERIOD_MS
#define CONTROL_TASK_PENDING_RESPONSE_CAPACITY APP_TX_RESPONSE_QUEUE_DEPTH
#define CONTROL_TASK_UNLOAD_RESET_TIMEOUT_MS 500U
#define CONTROL_ROUTE_MARKER_REARM_MS 30U
#define CONTROL_MARKER_APPROACH_PID_CORRECTION_LIMIT 40
#define CONTROL_TURN_REACQUIRE_BASE_PWM 280U
#define CONTROL_TURN_REACQUIRE_START_PWM 400U
#define CONTROL_TURN_REACQUIRE_START_MS 100U
#define CONTROL_TURN_REACQUIRE_PID_CORRECTION_LIMIT 100

#define CONTROL_HEALTH_MOTOR_INIT_FAILED 0x4D000001UL
#define CONTROL_HEALTH_MOTOR_OUTPUT_FAILED 0x4D000002UL
#define CONTROL_HEALTH_UNLOAD_RESET_TIMEOUT 0x4D000003UL
#define CONTROL_HEALTH_UNLOAD_RESET_RESULT_MISMATCH 0x4D000004UL

#if CONTROL_TASK_MAX_COMMANDS_PER_CYCLE == 0U
#error "ControlTask must process at least one command per cycle"
#endif

#if CONTROL_TASK_PENDING_RESPONSE_CAPACITY == 0U
#error "ControlTask pending response capacity must be greater than zero"
#endif

#if CONTROL_TASK_UNLOAD_RESET_TIMEOUT_MS <= APP_TIMING_UNLOAD_STEP_MS
#error "Unload reset timeout must exceed one UnloadTask cycle"
#endif

#if CONTROL_ROUTE_MARKER_REARM_MS < APP_TIMING_CONTROL_PERIOD_MS
#error "Route marker rearm time must cover at least one ControlTask cycle"
#endif

#if CONTROL_MARKER_APPROACH_PID_CORRECTION_LIMIT <= 0
#error "Marker approach PID correction limit must be greater than zero"
#endif

#if CONTROL_TURN_REACQUIRE_BASE_PWM == 0U || CONTROL_TURN_REACQUIRE_START_PWM < CONTROL_TURN_REACQUIRE_BASE_PWM || \
    CONTROL_TURN_REACQUIRE_START_MS == 0U || CONTROL_TURN_REACQUIRE_PID_CORRECTION_LIMIT <= 0
#error "Turn reacquisition motor settings must be greater than zero"
#endif

#endif /* CONTROL_CONFIG_H */
