#ifndef LINETRACER_CONTROL_TYPES_H
#define LINETRACER_CONTROL_TYPES_H

#include <stdint.h>

#include "logistics/contracts/uart/linetracer_commands.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Detailed states are private to the STM32 application. They deliberately do
 * not replace the stable, coarse-grained UART state values.
 */
typedef enum {
    LINETRACER_CONTROL_INITIALIZING = 0,
    LINETRACER_CONTROL_WAITING_AT_DEST,
    LINETRACER_CONTROL_TURNING_FROM_DEST,
    LINETRACER_CONTROL_MOVING_TO_SOURCE_JUNCTION,
    LINETRACER_CONTROL_MOVING_ON_COMMON_LINE,
    LINETRACER_CONTROL_TURNING_TO_PICKUP,
    LINETRACER_CONTROL_MOVING_TO_PICKUP,
    LINETRACER_CONTROL_PICKUP_READY,
    LINETRACER_CONTROL_WAITING_LOAD,
    LINETRACER_CONTROL_TURNING_AT_PICKUP,
    LINETRACER_CONTROL_MOVING_TO_DEST,
    LINETRACER_CONTROL_UNLOADING,
    LINETRACER_CONTROL_STOPPED,
    LINETRACER_CONTROL_OBSTACLE_STOP,
    LINETRACER_CONTROL_ERROR,
    LINETRACER_CONTROL_EMERGENCY_STOPPED
} linetracer_control_state_t;

typedef enum {
    LINETRACER_LINE_UNKNOWN = 0,
    LINETRACER_LINE_CENTERED,
    LINETRACER_LINE_LEFT_ONLY,
    LINETRACER_LINE_RIGHT_ONLY,
    LINETRACER_LINE_WHITE_GAP
} linetracer_line_state_t;

typedef enum {
    LINETRACER_TURN_NONE = 0,
    LINETRACER_TURN_LEFT,
    LINETRACER_TURN_RIGHT,
    LINETRACER_TURN_AROUND
} linetracer_turn_t;

typedef enum {
    LINETRACER_STOP_REASON_NONE = 0,
    LINETRACER_STOP_REASON_COMMAND,
    LINETRACER_STOP_REASON_OBSTACLE,
    LINETRACER_STOP_REASON_LINE_LOST,
    LINETRACER_STOP_REASON_LOAD_LOST,
    LINETRACER_STOP_REASON_OVERLOAD,
    LINETRACER_STOP_REASON_TURN_TIMEOUT,
    LINETRACER_STOP_REASON_MARKER_SEQUENCE,
    LINETRACER_STOP_REASON_COMM_TIMEOUT,
    LINETRACER_STOP_REASON_EMERGENCY,
    LINETRACER_STOP_REASON_SENSOR_FAULT
} linetracer_stop_reason_t;

#define LINETRACER_ROUTE_INDEX_INVALID 0xFFU

static inline uint8_t linetracer_route_index(uint32_t route_id) {
    if (uart_linetracer_route_is_valid(route_id) == 0U) {
        return LINETRACER_ROUTE_INDEX_INVALID;
    }

    return (uint8_t)(route_id - UART_LINETRACER_ROUTE_MIN);
}

static inline uart_linetracer_state_t linetracer_control_state_to_uart_state(linetracer_control_state_t state) {
    switch (state) {
        case LINETRACER_CONTROL_INITIALIZING:
        case LINETRACER_CONTROL_WAITING_AT_DEST:
            return UART_LINETRACER_STATE_IDLE;

        case LINETRACER_CONTROL_TURNING_FROM_DEST:
        case LINETRACER_CONTROL_TURNING_TO_PICKUP:
        case LINETRACER_CONTROL_TURNING_AT_PICKUP:
            return UART_LINETRACER_STATE_CORRECTING;

        case LINETRACER_CONTROL_MOVING_TO_SOURCE_JUNCTION:
        case LINETRACER_CONTROL_MOVING_ON_COMMON_LINE:
        case LINETRACER_CONTROL_MOVING_TO_PICKUP:
        case LINETRACER_CONTROL_MOVING_TO_DEST:
            return UART_LINETRACER_STATE_FOLLOWING_LINE;

        case LINETRACER_CONTROL_PICKUP_READY:
        case LINETRACER_CONTROL_WAITING_LOAD:
            return UART_LINETRACER_STATE_LOAD_WAIT;

        case LINETRACER_CONTROL_UNLOADING:
            return UART_LINETRACER_STATE_UNLOADING;

        case LINETRACER_CONTROL_STOPPED:
        case LINETRACER_CONTROL_OBSTACLE_STOP:
            return UART_LINETRACER_STATE_STOPPED;

        case LINETRACER_CONTROL_ERROR:
            return UART_LINETRACER_STATE_FAULT;

        case LINETRACER_CONTROL_EMERGENCY_STOPPED:
            return UART_LINETRACER_STATE_EMERGENCY_STOP;

        default:
            return UART_LINETRACER_STATE_FAULT;
    }
}

#ifdef __cplusplus
}
#endif

#endif /* LINETRACER_CONTROL_TYPES_H */
