#ifndef MOTOR_CONTROL_CONFIG_H
#define MOTOR_CONTROL_CONFIG_H

#define MOTOR_CONTROL_PWM_MAX 999U
#define MOTOR_CONTROL_LEFT_BASE_PWM 280U
#define MOTOR_CONTROL_RIGHT_BASE_PWM 280U
#define MOTOR_CONTROL_TRACKING_MIN_PWM 160U
#define MOTOR_CONTROL_TRACKING_FAST_BOOST_PWM 40U
#define MOTOR_CONTROL_LINE_RECOVERY_CORRECTION_PWM 80U
#define MOTOR_CONTROL_START_BOOST_PWM 340U
#define MOTOR_CONTROL_START_BOOST_MS 180U
#define MOTOR_CONTROL_LEFT_PIVOT_PWM 260U

#define MOTOR_CONTROL_RIGHT_PIVOT_PWM 230U
#define MOTOR_CONTROL_LEFT_TURN_RIGHT_PWM 250U
#define MOTOR_CONTROL_LEFT_UTURN_PWM 300U
#define MOTOR_CONTROL_RIGHT_UTURN_PWM 265U
#define MOTOR_CONTROL_LEFT_TRIM 0
#define MOTOR_CONTROL_RIGHT_TRIM 0

/* Set to 1 when a motor is wired opposite to the logical forward direction. */
#define MOTOR_CONTROL_LEFT_REVERSED 0U
#define MOTOR_CONTROL_RIGHT_REVERSED 0U

#if MOTOR_CONTROL_LEFT_BASE_PWM > MOTOR_CONTROL_PWM_MAX || MOTOR_CONTROL_RIGHT_BASE_PWM > MOTOR_CONTROL_PWM_MAX
#error "Motor base PWM values must fit the TIM3 period"
#endif

#if MOTOR_CONTROL_TRACKING_MIN_PWM > MOTOR_CONTROL_LEFT_BASE_PWM || \
    MOTOR_CONTROL_TRACKING_MIN_PWM > MOTOR_CONTROL_RIGHT_BASE_PWM
#error "Tracking minimum PWM must not exceed either calibrated base PWM"
#endif

#if (MOTOR_CONTROL_LEFT_BASE_PWM + MOTOR_CONTROL_TRACKING_FAST_BOOST_PWM > MOTOR_CONTROL_PWM_MAX) || \
    (MOTOR_CONTROL_RIGHT_BASE_PWM + MOTOR_CONTROL_TRACKING_FAST_BOOST_PWM > MOTOR_CONTROL_PWM_MAX)
#error "Tracking fast-wheel boost must fit the TIM3 period"
#endif

#if MOTOR_CONTROL_LINE_RECOVERY_CORRECTION_PWM == 0U
#error "Line recovery correction PWM must be greater than zero"
#endif

#if MOTOR_CONTROL_START_BOOST_PWM > MOTOR_CONTROL_PWM_MAX || MOTOR_CONTROL_START_BOOST_MS == 0U
#error "Motor start boost values must be valid"
#endif

#if MOTOR_CONTROL_LEFT_PIVOT_PWM > MOTOR_CONTROL_PWM_MAX || MOTOR_CONTROL_RIGHT_PIVOT_PWM > MOTOR_CONTROL_PWM_MAX
#error "Motor pivot PWM values must fit the TIM3 period"
#endif

#if MOTOR_CONTROL_LEFT_UTURN_PWM > MOTOR_CONTROL_PWM_MAX || MOTOR_CONTROL_RIGHT_UTURN_PWM > MOTOR_CONTROL_PWM_MAX
#error "Motor U-turn PWM values must fit the TIM3 period"
#endif

#if MOTOR_CONTROL_LEFT_REVERSED > 1U || MOTOR_CONTROL_RIGHT_REVERSED > 1U
#error "Motor reverse flags must be 0 or 1"
#endif

#endif /* MOTOR_CONTROL_CONFIG_H */
