#include "comm_rx_task.h"

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include "app_messages.h"
#include "app_queues.h"
#include "cmsis_os2.h"
#include "comm_rx_config.h"
#include "comm_rx_dispatch.h"
#include "comm_rx_logic.h"
#include "control_task.h"
#include "logistics/contracts/uart/linetracer_commands.h"
#include "logistics/contracts/uart_parser.h"
#include "stm32f4xx_hal.h"
#include "usart.h"

static uint8_t commRxDmaBuffer[COMM_RX_DMA_BUFFER_SIZE];
static uint8_t commRxProcessingBuffer[COMM_RX_DMA_BUFFER_SIZE];
static osThreadId_t commRxTaskId;
static volatile uint32_t commRxProducedBytes;
static volatile uint32_t commRxUartErrorCode;
static volatile uint16_t commRxDmaPosition;
static uint32_t commRxConsumedBytes;
static uint32_t commRxLastParserTickMs;
static uart_parser_t commRxParser;
static comm_rx_link_monitor_t commRxLinkMonitor;
static comm_rx_dispatch_t commRxDispatcher;
static comm_rx_stats_t commRxStats;
static uint8_t commRxRecoverableErrorActive;

/* Generated by CubeMX in freertos.c before the scheduler starts. */
extern osThreadId_t SafetyTaskHandle;

#if COMM_RX_DISPATCH_PENDING_CAPACITY != APP_TX_RESPONSE_QUEUE_DEPTH
#error "CommRx pending responses must match the response queue depth"
#endif

#if COMM_RX_DISPATCH_RESPONSE_RETRY_DELAY_MS != APP_TX_RESPONSE_RETRY_DELAY_MS
#error "CommRx response retry delay must match the application interface"
#endif

#if COMM_RX_DISPATCH_RESPONSE_MAX_RETRIES != APP_TX_RESPONSE_MAX_RETRIES
#error "CommRx response retry count must match the application interface"
#endif

static void CommRxTask_PublishHealthEvent(app_health_event_type_t type, uint32_t detail, uint32_t now_ms) {
    app_health_event_t event = { 0 };

    event.type = type;
    event.occurred_at_ms = now_ms;
    event.detail = detail;
    event.source_task = APP_TASK_COMM_RX;
    (void)AppQueues_TryPutHealth(&event);
}

static void CommRxTask_ReportRecoverableError(uint32_t detail, uint32_t now_ms) {
    if (commRxRecoverableErrorActive == 0U) {
        CommRxTask_PublishHealthEvent(APP_HEALTH_EVENT_UART_RX_ERROR, detail, now_ms);
        commRxRecoverableErrorActive = 1U;
    }
}

static void CommRxTask_ReportRecovered(uint32_t detail, uint32_t now_ms) {
    if (commRxRecoverableErrorActive != 0U) {
        CommRxTask_PublishHealthEvent(APP_HEALTH_EVENT_UART_RX_RECOVERED, detail, now_ms);
        commRxRecoverableErrorActive = 0U;
    }
}

static uint8_t CommRxTask_LinkMonitoringRequired(void) {
    app_control_snapshot_t snapshot;

    if (!ControlTask_GetLatest(&snapshot)) {
        return 0U;
    }

    return (uart_linetracer_job_id_is_valid(snapshot.job_id) != 0U &&
            uart_linetracer_route_is_valid(snapshot.route_id) != 0U)
               ? 1U
               : 0U;
}

static uint8_t CommRxTask_PutControl(void* context, const app_control_command_t* command) {
    (void)context;
    return (controlCommandQueue != NULL && osMessageQueuePut(controlCommandQueue, command, 0U, 0U) == osOK) ? 1U : 0U;
}

static uint8_t CommRxTask_PutSafety(void* context, const app_safety_event_t* event, uint8_t priority) {
    (void)context;
    return (safetyEventQueue != NULL && osMessageQueuePut(safetyEventQueue, event, priority, 0U) == osOK) ? 1U : 0U;
}

static uint8_t CommRxTask_NotifyEmergency(void* context) {
    uint32_t result;

    (void)context;
    if (SafetyTaskHandle == NULL) {
        return 0U;
    }

    result = osThreadFlagsSet(SafetyTaskHandle, APP_SAFETY_NOTIFY_EMERGENCY_STOP);
    return ((result & osFlagsError) == 0U) ? 1U : 0U;
}

static uint8_t CommRxTask_PutResponse(void* context, const app_tx_event_t* event) {
    (void)context;
    return (AppQueues_TryPutTx(event) == osOK) ? 1U : 0U;
}

static void CommRxTask_ReportHealth(void* context, app_health_event_type_t type, uint32_t detail, uint32_t now_ms) {
    (void)context;
    CommRxTask_PublishHealthEvent(type, detail, now_ms);
}

static const comm_rx_dispatch_port_t commRxDispatchPort = {
    .context = NULL,
    .put_control = CommRxTask_PutControl,
    .put_safety = CommRxTask_PutSafety,
    .notify_emergency = CommRxTask_NotifyEmergency,
    .put_response = CommRxTask_PutResponse,
    .report_health = CommRxTask_ReportHealth,
};

static void CommRxTask_ApplyDispatchEffects(const comm_rx_dispatch_effects_t* effects) {
    if (effects == NULL) {
        return;
    }

    commRxStats.control_commands += effects->control_commands;
    commRxStats.safety_commands += effects->safety_commands;
    commRxStats.local_responses += effects->local_responses;
    commRxStats.duplicate_sequences += effects->duplicate_sequences;
    commRxStats.invalid_payloads += effects->invalid_payloads;
    commRxStats.unsupported_commands += effects->unsupported_commands;
    commRxStats.queue_drops += effects->queue_drops;
    commRxStats.response_retries += effects->response_retries;
    commRxStats.response_timeouts += effects->response_timeouts;
}

static void CommRxTask_ResetReceptionState(void) {
    commRxProducedBytes = 0U;
    commRxConsumedBytes = 0U;
    commRxDmaPosition = 0U;
}

static void CommRxTask_ResetParser(void) {
    uart_parser_reset(&commRxParser);
    commRxLastParserTickMs = osKernelGetTickCount();
}

static HAL_StatusTypeDef CommRxTask_StartDma(void) {
    CommRxTask_ResetReceptionState();
    return HAL_UARTEx_ReceiveToIdle_DMA(&huart6, commRxDmaBuffer, (uint16_t)COMM_RX_DMA_BUFFER_SIZE);
}

static uint16_t CommRxTask_NormalizeDmaPosition(uint16_t position) {
    return (position >= COMM_RX_DMA_BUFFER_SIZE) ? 0U : position;
}

static uint16_t CommRxTask_BytesSinceLastEvent(uint16_t current_position, uint16_t previous_position) {
    if (current_position >= previous_position) {
        return (uint16_t)(current_position - previous_position);
    }

    return (uint16_t)(COMM_RX_DMA_BUFFER_SIZE - previous_position + current_position);
}

static void CommRxTask_RecordDmaEvent(uint16_t position) {
    uint16_t current_position;
    uint16_t previous_position;
    uint16_t received_bytes;

    if (position > COMM_RX_DMA_BUFFER_SIZE) {
        commRxUartErrorCode |= HAL_UART_ERROR_DMA;
        if (commRxTaskId != NULL) {
            (void)osThreadFlagsSet(commRxTaskId, APP_COMM_RX_NOTIFY_UART_ERROR);
        }
        return;
    }

    current_position = CommRxTask_NormalizeDmaPosition(position);
    previous_position = commRxDmaPosition;
    received_bytes = CommRxTask_BytesSinceLastEvent(current_position, previous_position);
    commRxDmaPosition = current_position;

    if (received_bytes == 0U) {
        return;
    }

    __DMB();
    commRxProducedBytes += received_bytes;
    if (commRxTaskId != NULL) {
        (void)osThreadFlagsSet(commRxTaskId, APP_COMM_RX_NOTIFY_DATA_READY);
    }
}

static void CommRxTask_DrainDmaBuffer(uint32_t now_ms) {
    uint32_t produced_bytes;
    uint32_t available_bytes;

    for (;;) {
        produced_bytes = commRxProducedBytes;
        __DMB();
        available_bytes = produced_bytes - commRxConsumedBytes;

        if (available_bytes == 0U) {
            return;
        }

        if (available_bytes >= COMM_RX_DMA_BUFFER_SIZE) {
            uint32_t dropped_bytes = available_bytes;

            commRxConsumedBytes = produced_bytes;
            CommRxTask_ResetParser();
            CommRxTask_ReportRecoverableError(COMM_RX_HEALTH_DMA_OVERRUN | (dropped_bytes & 0x00FFFFFFUL), now_ms);
            continue;
        }

        while (available_bytes > 0U) {
            uint32_t read_position = commRxConsumedBytes % COMM_RX_DMA_BUFFER_SIZE;
            uint32_t contiguous_bytes = COMM_RX_DMA_BUFFER_SIZE - read_position;
            uint32_t produced_after_copy;

            if (contiguous_bytes > available_bytes) {
                contiguous_bytes = available_bytes;
            }

            memcpy(commRxProcessingBuffer, &commRxDmaBuffer[read_position], contiguous_bytes);
            __DMB();
            produced_after_copy = commRxProducedBytes;
            if ((produced_after_copy - commRxConsumedBytes) >= COMM_RX_DMA_BUFFER_SIZE) {
                uint32_t dropped_bytes = produced_after_copy - commRxConsumedBytes;

                commRxConsumedBytes = produced_after_copy;
                CommRxTask_ResetParser();
                CommRxTask_ReportRecoverableError(COMM_RX_HEALTH_DMA_OVERRUN | (dropped_bytes & 0x00FFFFFFUL), now_ms);
                break;
            }

            CommRxTask_ProcessReceivedBytes(commRxProcessingBuffer, (uint16_t)contiguous_bytes);
            commRxConsumedBytes += contiguous_bytes;
            available_bytes -= contiguous_bytes;
        }
    }
}

static void CommRxTask_HandleUartError(uint32_t now_ms) {
    uint32_t interrupt_state = __get_PRIMASK();
    uint32_t uart_error;

    __disable_irq();
    uart_error = commRxUartErrorCode;
    commRxUartErrorCode = HAL_UART_ERROR_NONE;
    if (interrupt_state == 0U) {
        __enable_irq();
    }

    (void)HAL_UART_AbortReceive(&huart6);
    CommRxTask_ResetParser();
    CommRxTask_ReportRecoverableError(COMM_RX_HEALTH_UART_ERROR | (uart_error & 0x00FFFFFFUL), now_ms);
}

static void CommRxTask_StartDmaUntilReady(void) {
    for (;;) {
        uint32_t now_ms = osKernelGetTickCount();

        if (CommRxTask_StartDma() == HAL_OK) {
            CommRxTask_ReportRecovered(COMM_RX_HEALTH_DMA_START_FAILED, now_ms);
            return;
        }

        CommRxTask_ReportRecoverableError(COMM_RX_HEALTH_DMA_START_FAILED, now_ms);
        osDelay(COMM_RX_DMA_RESTART_DELAY_MS);
    }
}

static void CommRxTask_ProcessPendingResponses(uint32_t now_ms) {
    comm_rx_dispatch_effects_t effects;

    CommRxDispatch_ProcessPending(&commRxDispatcher, &commRxDispatchPort, now_ms, &effects);
    CommRxTask_ApplyDispatchEffects(&effects);
}

static void CommRxTask_DispatchFrame(const uart_frame_t* frame, uint32_t now_ms) {
    comm_rx_dispatch_effects_t effects;

    ++commRxStats.received_frames;
    CommRxDispatch_Frame(&commRxDispatcher, &commRxDispatchPort, frame, now_ms, &effects);
    CommRxTask_ApplyDispatchEffects(&effects);
}

static void CommRxTask_ReportParserError(uart_parser_result_t result) {
    (void)result;
    ++commRxStats.parser_errors;
}

void CommRxTask_ProcessReceivedBytes(const uint8_t* data, uint16_t length) {
    uint16_t index;
    uint32_t now_ms;

    if (data == NULL || length == 0U) {
        return;
    }

    now_ms = osKernelGetTickCount();
    commRxStats.received_bytes += length;
    CommRxLogic_LinkRecordRaw(&commRxLinkMonitor, now_ms);
    commRxStats.last_raw_activity_ms = commRxLinkMonitor.last_raw_activity_ms;
    commRxLastParserTickMs = now_ms;

    for (index = 0U; index < length; ++index) {
        uart_frame_t frame;
        uart_parser_result_t result = uart_parser_feed(&commRxParser, data[index], &frame);

        if (result == UART_PARSER_FRAME_READY) {
            const uint8_t timeout_was_active = commRxLinkMonitor.timeout_reported;
            const uint8_t recoverable_error_was_active = commRxRecoverableErrorActive;

            CommRxLogic_LinkRecordValidFrame(&commRxLinkMonitor, now_ms);
            commRxStats.last_valid_frame_ms = commRxLinkMonitor.last_valid_frame_ms;
            if (timeout_was_active != 0U && recoverable_error_was_active == 0U) {
                CommRxTask_PublishHealthEvent(APP_HEALTH_EVENT_UART_RX_RECOVERED, commRxStats.received_frames, now_ms);
            }
            CommRxTask_ReportRecovered(commRxStats.received_frames, now_ms);
            CommRxTask_DispatchFrame(&frame, now_ms);
        } else if (result < UART_PARSER_NO_FRAME) {
            CommRxTask_ReportParserError(result);
        }
    }
}

static void CommRxTask_ServiceTimers(uint32_t now_ms) {
    uint32_t elapsed_ms = now_ms - commRxLastParserTickMs;
    uint8_t monitoring_required;
    uart_parser_result_t parser_result;

    commRxLastParserTickMs = now_ms;
    parser_result = uart_parser_tick(&commRxParser, elapsed_ms);
    if (parser_result < UART_PARSER_NO_FRAME) {
        CommRxTask_ReportParserError(parser_result);
    }

    monitoring_required = CommRxTask_LinkMonitoringRequired();
    if (CommRxLogic_LinkSetMonitoringRequired(&commRxLinkMonitor, monitoring_required, now_ms) != 0U) {
        CommRxTask_PublishHealthEvent(APP_HEALTH_EVENT_UART_RX_RECOVERED, 0U, now_ms);
    }

    if (CommRxLogic_LinkCheckTimeout(&commRxLinkMonitor, now_ms, COMM_RX_LINK_TIMEOUT_MS) != 0U) {
        ++commRxStats.link_timeouts;
        CommRxTask_PublishHealthEvent(APP_HEALTH_EVENT_UART_RX_TIMEOUT, now_ms - commRxLinkMonitor.last_valid_frame_ms,
                                      now_ms);
    }
}

void CommRxTask_GetStats(comm_rx_stats_t* stats) {
    if (stats != NULL) {
        *stats = commRxStats;
    }
}

void HAL_UARTEx_RxEventCallback(UART_HandleTypeDef* huart, uint16_t size) {
    if ((huart != NULL) && (huart->Instance == USART6)) {
        CommRxTask_RecordDmaEvent(size);
    }
}

void HAL_UART_ErrorCallback(UART_HandleTypeDef* huart) {
    if ((huart == NULL) || (huart->Instance != USART6)) {
        return;
    }

    commRxUartErrorCode |= huart->ErrorCode;
    if (commRxTaskId != NULL) {
        (void)osThreadFlagsSet(commRxTaskId, APP_COMM_RX_NOTIFY_UART_ERROR);
    }
}

void StartCommRxTask(void* argument) {
    uint32_t last_alive_ms;
    uint32_t now_ms;

    (void)argument;
    commRxTaskId = osThreadGetId();
    now_ms = osKernelGetTickCount();
    last_alive_ms = now_ms;
    commRxLastParserTickMs = now_ms;
    memset(&commRxStats, 0, sizeof(commRxStats));
    commRxRecoverableErrorActive = 0U;
    CommRxLogic_LinkInit(&commRxLinkMonitor, now_ms);
    CommRxDispatch_Init(&commRxDispatcher);
    commRxStats.last_raw_activity_ms = commRxLinkMonitor.last_raw_activity_ms;
    commRxStats.last_valid_frame_ms = commRxLinkMonitor.last_valid_frame_ms;
    uart_parser_init(&commRxParser);

    CommRxTask_StartDmaUntilReady();

    for (;;) {
        uint32_t flags = osThreadFlagsWait(APP_COMM_RX_NOTIFY_DATA_READY | APP_COMM_RX_NOTIFY_UART_ERROR,
                                           osFlagsWaitAny, COMM_RX_TASK_SERVICE_INTERVAL_MS);
        now_ms = osKernelGetTickCount();

        if ((flags & osFlagsError) != 0U) {
            if (flags != osFlagsErrorTimeout) {
                CommRxTask_PublishHealthEvent(APP_HEALTH_EVENT_INTERNAL_ERROR,
                                              COMM_RX_HEALTH_FLAG_WAIT_ERROR | (flags & 0x00FFFFFFUL), now_ms);
            }
        } else {
            if ((flags & APP_COMM_RX_NOTIFY_UART_ERROR) != 0U) {
                CommRxTask_HandleUartError(now_ms);
                CommRxTask_StartDmaUntilReady();
                ++commRxStats.uart_restarts;
                now_ms = osKernelGetTickCount();
            } else if ((flags & APP_COMM_RX_NOTIFY_DATA_READY) != 0U) {
                CommRxTask_DrainDmaBuffer(now_ms);
            }
        }

        CommRxTask_ProcessPendingResponses(now_ms);
        CommRxTask_ServiceTimers(now_ms);

        if ((uint32_t)(now_ms - last_alive_ms) >= COMM_RX_TASK_ALIVE_INTERVAL_MS) {
            CommRxTask_PublishHealthEvent(APP_HEALTH_EVENT_TASK_ALIVE, commRxConsumedBytes, now_ms);
            last_alive_ms = now_ms;
        }
    }
}
