#ifndef SORTING_GATE_MG90S_H
#define SORTING_GATE_MG90S_H

#include "sorting_gate.h"

/*
 * TIM3 is configured for 1 us/count and a 20 ms (50 Hz) period.
 *
 * Gate A: MG90S on TIM3_CH2 / PC7
 * Gate B: SG90  on TIM3_CH3 / PC8
 *
 * Calibrate the installation by changing only the pulse values below.
 */
#ifndef SORTING_GATE_MG90S_HOME_PULSE_US
#define SORTING_GATE_MG90S_HOME_PULSE_US 1500U
#endif

#ifndef SORTING_GATE_MG90S_DESTINATION_1_PULSE_US
#define SORTING_GATE_MG90S_DESTINATION_1_PULSE_US 850U
#endif

#ifndef SORTING_GATE_MG90S_DESTINATION_2_PULSE_US
#define SORTING_GATE_MG90S_DESTINATION_2_PULSE_US SORTING_GATE_MG90S_HOME_PULSE_US
#endif

#ifndef SORTING_GATE_MG90S_DESTINATION_3_PULSE_US
#define SORTING_GATE_MG90S_DESTINATION_3_PULSE_US SORTING_GATE_MG90S_HOME_PULSE_US
#endif

#ifndef SORTING_GATE_SG90_HOME_PULSE_US
#define SORTING_GATE_SG90_HOME_PULSE_US 1500U
#endif

#ifndef SORTING_GATE_SG90_DESTINATION_1_PULSE_US
#define SORTING_GATE_SG90_DESTINATION_1_PULSE_US SORTING_GATE_SG90_HOME_PULSE_US
#endif

#ifndef SORTING_GATE_SG90_DESTINATION_2_PULSE_US
#define SORTING_GATE_SG90_DESTINATION_2_PULSE_US 1100U
#endif

#ifndef SORTING_GATE_SG90_DESTINATION_3_PULSE_US
#define SORTING_GATE_SG90_DESTINATION_3_PULSE_US SORTING_GATE_SG90_HOME_PULSE_US
#endif

#ifndef SORTING_GATE_SETTLE_TIME_MS
#define SORTING_GATE_SETTLE_TIME_MS 500U
#endif

const sorting_gate_port_t* sorting_gate_mg90s_port(void);

#endif /* SORTING_GATE_MG90S_H */
